pipeline:
  test:
    image: python:3.6-alpine
    commands:
      - apk add --update gcc musl-dev
      - pip install -r requirements-dev.txt
      - mkdir logs
      - tox
    secrets: [ omnomnom_auth_token, omnomnom_admin ]
    when:
      branch: [ master, dev ]
  bdist_wheel:
    image: python:3.6-alpine
    commands:
      - python setup.py bdist_wheel
    when:
      branch: [ master, dev ]
  docker:
    image: plugins/docker
    repo: ekeih/omnomnom
    secrets: [ docker_username, docker_password ]
    tag: ${DRONE_BRANCH/\//-}
    when:
      branch: [ master, dev ]
  github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: dist/*
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
    when:
      event: tag
  telegram:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    when:
      status: [ success, failure ]