pipeline:
  run_tests:
    image: python:3.6-alpine
    commands:
      - apk add --update gcc musl-dev libmagic poppler-utils
      - pip install -r requirements-dev.txt
      - mkdir logs
      - tox
    secrets: [ omnomnom_auth_token, omnomnom_admin ]
    when:
      event: [ push, tag ]
  build_python_package:
    image: python:3.6-alpine
    commands:
      - python setup.py bdist_wheel
    when:
      event: [ push, tag ]
  build_docs:
    image: python:3.6-alpine
    commands:
      - apk add --update gcc musl-dev make
      - pip install -r requirements.txt -r docs/requirements.txt
      - cd docs && make html
    secrets: [ omnomnom_auth_token, omnomnom_admin ]
    when:
      event: tag
  build_docs_docker_image:
    image: plugins/docker
    repo: ekeih/omnomnom-docs
    secrets: [ docker_username, docker_password ]
    context: docs
    dockerfile: docks/Dockerfile
    when:
      event: tag
  build_docker_image:
    image: plugins/docker
    repo: ekeih/omnomnom
    secrets: [ docker_username, docker_password ]
    tag: ${DRONE_BRANCH}
    when:
      event: push
  push_github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: dist/*
    checksum:
      - md5
      - sha1
      - sha256
      - sha512
    when:
      event: tag
  telegram_hook:
    image: appleboy/drone-telegram
    secrets: [ telegram_token, telegram_to ]
    when:
      status: [ success, failure ]